### ISSUE TITLE
Update the overlay

### ISSUE THREAD

**Issue by ishboo** [fragment-nine/Show-Saver#28]
I'd like to add labels like Song: LTC: Date: and see if we can get away with slightly smaller text. Try it in a banner across the bottom so it's not overlaid on too much screen real estate, I found myself looking at stuff behind the text often on HU. Long term we could have different layouts or customizable layouts.

**Comment by ishboo** [comment]
Reopening this to make some modifications to it

**Comment by andrewgange** [comment]
copy above - what changes need to be done on this? do we want to implement more control of the overlay from the UI?
